
[[project]]
repo = "jiacai2050/zigcli"
lang = ["Zig"]
description = "A toolkit for building command line programs in Zig."

[[project]]
repo = "jiacai2050/zig-curl"
lang = ["Zig"]
description = "Libcurl bindings for Zig"

[[project]]
repo = "jiacai2050/comptime-serde"
lang = ["Zig"]
description = "Compile-time serialization and deserialization for Zig."

[[project]]
repo = "jiacai2050/zllm"
lang = ["Zig"]
description = "A lightweight, high-performance LLM inference engine for macOS Apple Silicon"

[[project]]
repo = "zigcc/zig-cookbook"
lang = ["Zig"]
description = "Simple Zig programs that demonstrate good practices to accomplish common programming tasks."

[[project]]
repo = "jiacai2050/flauth"
lang = ["Dart"]
description = "A privacy-first, fully open-source TOTP authenticator"

[[project]]
repo = "jiacai2050/ai-menshen"
lang = ["Go"]
description = "A lightweight, local-first AI Gateway."

[[project]]
repo = "localfirstapp/1History"
lang = ["Rust", "JS"]
description = """
Backup/visualize browser histories.
"""

[[project]]
repo = "jiacai2050/my-works"
lang = ["Python", "JS"]
description = """
Monorepo of my public softwares: [ShellGPT](https://pypi.org/project/shgpt/), [Gooreplacer](https://liujiacai.net/gooreplacer/) [TextSaver](https://liujiacai.net/text-saver/), [LinkPreview](https://liujiacai.net/link-preview/), [VideoCompress](https://pypi.org/project/video-compress/)
"""

[[project]]
repo = "jiacai2050/edgebin"
lang = ["JS"]
description = "A minimalist HTTP service designed to test your networking stack."

[[project]]
repo = "zigcc/awesome-zig"
lang = ["markdown"]
description = "A collaborative list of awesome Zig libraries and resources."

[[project]]
repo = "zigcc/zigcc.github.io"
lang = ["markdown"]
description = "Zig Chinese Community Website"

[[project]]
repo = "jiacai2050/zig-napi"
lang = ["Zig"]
description = "[Node-API(N-API)](https://nodejs.org/api/n-api.html) bindings for Zig"

[[project]]
repo = "jiacai2050/zig-emacs"
lang = ["Zig"]
description = "Emacs [dynamic modules](https://www.gnu.org/software/emacs/manual/html_node/elisp/Writing-Dynamic-Modules.html) bindings for Zig"

[[project]]
repo = "jiacai2050/sendmail-action"
lang = ["Bash"]
description = "A GitHub Composite Action to send text and/or HTML emails via SMTP using curl."

[[project]]
repo = "jiacai2050/mastodon-action"
lang = ["JS"]
description = "A GitHub Action to post Mastodon status updates"

[[project]]
repo = "jiacai2050/telegraph-action"
lang = ["JS"]
description = "A GitHub Action to create a Telegraph post from a markdown file."

[[project]]
repo = "jiacai2050/telegram-action"
lang = ["JS"]
description = "A GitHub Action allows you to send messages to a Telegram chat using a bot."